# CI CD using GitHub Actions
name: CI CD Pipeline

#Exlude the workflow to run on chnages to helm chart files
on:
  push:
    branches: 
      - main
    paths-ignore: 
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build the Go application
        run: go build -o go-web-app .

      - name: Run tests
        run: go test ./...

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2
  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/go-web-app:${{ github.sha }}
          
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update image tag in Helm chart
        run: |
          sed -i  's/tag: .*/tag: "{{github.run_id}}"/' helm/go-web-app-charts/values.yaml
          
      - name: Commit and push changes
        run: |
          git config --global user.email "naiala_sandeep@yahoo.com"
          git config --global user.name "sandeepnainala"
          git add helm/go-web-app-charts/values.yaml
          git commit -m "Update image tag in Helm"
          git push origin main